# Generated by Django 4.2.5 on 2023-09-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budget_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
    ]
